import { defineType, defineField } from 'sanity'

export const sectorLanding = defineType({
  name:  'sectorLanding',
  title: 'Landing de sector',
  type:  'document',
  fields: [
    defineField({ name: 'sector', title: 'Sector (slug)', type: 'slug',
      description: 'Debe coincidir con el ID del sector (ej: peluqueria, fisioterapia)',
      options: { source: 'schema_name' },
      validation: r => r.required(),
    }),
    defineField({ name: 'schema_name', title: 'Nombre para Schema.org', type: 'string',
      description: 'Ej: MyMarketing para Peluquerías',
      validation: r => r.required(),
    }),
    defineField({ name: 'headline', title: 'Titular principal', type: 'string',
      validation: r => r.required().max(80),
    }),
    defineField({ name: 'subheadline', title: 'Subtítulo', type: 'string',
      validation: r => r.max(160),
    }),
    defineField({ name: 'pain_points', title: 'Problemas del sector', type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({ name: 'features', title: 'Funcionalidades destacadas', type: 'array',
      of: [{
        type: 'object',
        fields: [
          { name: 'title',       type: 'string', title: 'Título' },
          { name: 'description', type: 'text',   title: 'Descripción' },
          { name: 'icon',        type: 'string', title: 'Emoji icono' },
        ],
      }],
    }),
    defineField({ name: 'testimonials', title: 'Testimonios', type: 'array',
      of: [{
        type: 'object',
        fields: [
          { name: 'name',     type: 'string', title: 'Nombre' },
          { name: 'business', type: 'string', title: 'Negocio' },
          { name: 'quote',    type: 'text',   title: 'Cita' },
        ],
      }],
    }),
    defineField({ name: 'cta_text', title: 'Texto del botón CTA', type: 'string',
      initialValue: 'Empieza gratis 15 días',
    }),
    defineField({ name: 'seo_title', title: 'Título SEO', type: 'string',
      validation: r => r.max(70),
    }),
    defineField({ name: 'seo_description', title: 'Meta description', type: 'text',
      validation: r => r.max(160),
    }),
  ],
  preview: {
    select: { title: 'headline', subtitle: 'sector.current' },
  },
})
